const fs = require("fs");
async function generate() {
    const commandFiles = fs
        .readdirSync("./commands/")
        .filter((file) => file.endsWith(".js"));
    let infoArr = commandFiles.map((file) => {
        const command = require(`../commands/${file}`);
        return {
            name: command.name,
            usage: `\`${command.usage === undefined ? "-" : command.usage}\``,
            description: `${command.description === undefined ? "-" : command.description}`,
        };
    });

    infoArr.sort();
    let data = ['Auto-generated by generate_command_readme.js\n\n', '## Commands'];
    for (const command of infoArr) {
        data.push(`\n#### ${command.name}`);
        data.push(`\nUsage: ${command.usage}`)
        data.push(`Description: ${command.description}`)
    }
    fs.writeFileSync('commands.md', data.join('\n'));
    console.log('Generated commands.md');
}


; (async () => {
    await generate();
})()
