name: Deploy VM
on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Deploying to VM
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.KEY }}
                  script: |
                      export NVM_DIR=~/.nvm
                      source ~/.nvm/nvm.sh
                      cd apps/oogway
                      git checkout master
                      git fetch --all
                      git reset --hard origin/master
                      npm run-script docker-prod-build
                      npm run-script docker-prod-run
