name: Deploy VM
on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Deploying to VM
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.KEY }}
                  script: |
                      cd apps/oogway
                      sudo git checkout master
                      sudo git fetch --all
                      sudo git reset --hard origin/master
                      sudo npm run-script docker-prod-build
                      sudo npm run-script docker-prod-run
